version: "3"
# each container will be refers as service
services:
  nginx:
    ports:
      - "8888:80" # nginx listen port 80
  # name of container
  node-app:
    build:
      context: . # dockerfile
      args: 
        NODE_ENV: development
    volumes:
    # bind mount 
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env
    command: npm run dev
