version: "3"
# each container will be refers as service
services:
  # name of container
  node-app:
    build:
      context: . # dockerfile
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js