version: "3"
# each container will be refers as service
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8888:80"
    volumes:
      # bind mount 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  # name of container
  node-app:
    image: kovite/node-app:latest
    build: .
    # ports:
    #   - "8888:8888"
    environment:
      - PORT=8888
    depends_on:
      - mongo # start mongo container
      - redis
  # mongo container
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.docker.env
    volumes:
      # save volume mongo-db
      - mongo-db:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
    
# named volume
volumes:
  mongo-db: