version: "3"
# each container will be refers as service
services:
  # name of container
  node-app:
    build: .
    ports:
      - "8888:4000"
    environment:
      - PORT=4000
    depends_on:
      - mongo # start mongo container
  # mongo container
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.docker.env
    volumes:
      # save volume mongo-db
      - mongo-db:/data/db
# named volume
volumes:
  mongo-db: