version: "3"
# each container will be refers as service
services:
  # name of container
  node-app:
    build: .
    ports:
      - "8888:8888"
    environment:
      - PORT=8888
    depends_on:
      - mongo # start mongo container
      - redis
  # mongo container
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.docker.env
    volumes:
      # save volume mongo-db
      - mongo-db:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
    
# named volume
volumes:
  mongo-db: